"""Regenerate THIRD_PARTY_NOTICES.md from the installed runtime dependencies.

    uv run python tools/generate_third_party_notices.py

Walks the runtime dependency closure of the `dicompurge` distribution (no
dev group, no extras) using the metadata of what is actually installed, and
reproduces every license and notice file each wheel ships. Packages that
ship no license text in their wheel (the PySide6 family) are covered by the
texts kept in tools/licenses/, which also carry the GPL-3.0 text the LGPL
refers to and the PSF license for Python itself.
"""
from __future__ import annotations

import sys
from collections import deque
from datetime import date
from importlib import metadata
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD_PARTY_NOTICES.md"
TEXTS = ROOT / "tools" / "licenses"
APP = "dicompurge"

# Wheels with no license file: which text in tools/licenses/ covers them.
EXTERNAL_TEXTS = {
    "pyside6": ["LGPL-3.0.txt"],
    "pyside6-addons": ["LGPL-3.0.txt"],
    "pyside6-essentials": ["LGPL-3.0.txt"],
    "shiboken6": ["LGPL-3.0.txt"],
}

# Human notes shown in the inventory, keyed by canonical name.
NOTES = {
    "pylibjpeg-libjpeg": "GPL-3.0. Wraps Thomas Richter's libjpeg (JPEG, JPEG-LS, JPEG XT decoding). See the GPL section above.",
    "pyside6": "LGPL-3.0 chosen from the LGPL/GPL/commercial options. See the LGPL section above.",
    "pyside6-addons": "Part of PySide6; LGPL-3.0.",
    "pyside6-essentials": "Part of PySide6; LGPL-3.0.",
    "shiboken6": "PySide6's binding generator runtime; LGPL-3.0.",
    "numpy": "BSD-3-Clause, with bundled components under 0BSD, MIT, Zlib and CC0 (texts reproduced below).",
    "packaging": "Dual Apache-2.0 / BSD-2-Clause; used under BSD-2-Clause.",
    "python-dateutil": "Dual Apache-2.0 / BSD-3-Clause; used under BSD-3-Clause.",
}

HEADER = """# Third-party notices for DicomPurge

DicomPurge is written in Python and depends on the open-source packages listed
below. This file reproduces their license terms and notices as those licenses
require. It is generated by `tools/generate_third_party_notices.py` from the
packages actually installed; regenerate it after changing dependencies.

Generated {today} from the lock file for DicomPurge {version} on Python {python}.

## Summary of obligations

Every package below is under a permissive license (MIT, BSD, Apache-2.0,
MIT-CMU, MPL-2.0, PSF) **except two**, which carry obligations of their own:

### PySide6 / shiboken6 - LGPL-3.0

Qt for Python is used under the GNU Lesser General Public License v3.0 (it is
also offered under GPL-2.0, GPL-3.0 and commercial terms; DicomPurge takes the
LGPL option). Under LGPL-3.0 sections 4 and 5, when DicomPurge is conveyed:

- this notice and the LGPL-3.0 text (and the GPL-3.0 text it incorporates)
  accompany it - both are reproduced at the end of this file;
- PySide6 remains a separately replaceable component. DicomPurge loads it as
  the ordinary `PySide6` wheels from PyPI, dynamically, and never modifies it,
  so a user can substitute a different version by reinstalling the package;
- any modification DicomPurge made to PySide6 or Qt itself would have to be
  released under the LGPL. None is made.

Qt itself bundles further third-party components (FFmpeg, ICU, PCRE2, zlib
and others); their attributions are listed by The Qt Company at
<https://doc.qt.io/qt-6/licenses-used-in-qt.html>.

### pylibjpeg-libjpeg - GPL-3.0

`pylibjpeg-libjpeg` is a pydicom decoding plugin for JPEG, JPEG-LS and JPEG XT
transfer syntaxes. Both the plugin and the C++ libjpeg it wraps are licensed
under the GNU General Public License v3.0 **only**. GPL-3.0 is a copyleft
license: a work that incorporates GPL code and is conveyed to others must be
licensed as a whole under GPL-3.0, with its complete corresponding source made
available (GPL-3.0 sections 5 and 6).

DicomPurge is therefore itself released under GPL-3.0-only (see `LICENSE`),
which satisfies this condition: anyone conveying DicomPurge must pass on the
GPL-3.0 terms and make the corresponding source available. `pylibjpeg` (the
plugin framework) and `pylibjpeg-openjpeg` are MIT and carry no such condition.

### Python

The interpreter itself is under the Python Software Foundation License
(PSF-2.0), reproduced at the end of this file.

## Inventory

Runtime dependencies only: the packages `uv` installs for DicomPurge without
the `dev` group. Test and release tooling (pytest, bump-my-version) is not
distributed with the application and is not listed.

| Package | Version | License | Homepage | Note |
| --- | --- | --- | --- | --- |"""


def _dist(name: str):
    return metadata.distribution(name)


def _closure(start: str) -> list[metadata.Distribution]:
    seen: dict[str, metadata.Distribution] = {}
    queue = deque([start])
    while queue:
        name = queue.popleft()
        key = canonicalize_name(name)
        if key in seen:
            continue
        try:
            dist = _dist(name)
        except metadata.PackageNotFoundError:
            print(f"warning: {name} is not installed; skipped", file=sys.stderr)
            continue
        seen[key] = dist
        for req_text in dist.requires or []:
            req = Requirement(req_text)
            if req.marker is not None and not req.marker.evaluate({"extra": ""}):
                continue
            queue.append(req.name)
    seen.pop(canonicalize_name(start), None)
    return sorted(seen.values(), key=lambda d: d.metadata["Name"].lower())


def _license(dist) -> str:
    m = dist.metadata
    expr = m.get("License-Expression")
    if expr:
        return expr
    classifiers = [c for c in (m.get_all("Classifier") or []) if c.startswith("License ::")]
    if classifiers:
        return "; ".join(c.split("::")[-1].strip() for c in classifiers)
    text = (m.get("License") or "").strip()
    return text.splitlines()[0][:60] if text else "(see text)"


def _homepage(dist) -> str:
    """A project page, never a changelog (some wheels put that in Home-page)."""
    m = dist.metadata
    candidates = []
    if m.get("Home-page"):
        candidates.append(("homepage", m["Home-page"]))
    for url in m.get_all("Project-URL") or []:
        label, _, target = url.partition(",")
        candidates.append((label.strip().lower(), target.strip()))
    preferred = ("homepage", "home", "source", "source code", "repository", "code", "documentation")
    for label in preferred:
        for cand_label, target in candidates:
            if cand_label == label and "change" not in target.lower():
                return target
    for _, target in candidates:
        if "change" not in target.lower():
            return target
    return candidates[0][1] if candidates else ""


def _license_files(dist) -> list[tuple[str, str]]:
    """(display name, text) for every license/notice file the wheel ships."""
    out = []
    for f in dist.files or []:
        rel = str(f)
        base = rel.rsplit("/", 1)[-1].upper()
        if ".dist-info" not in rel:
            continue
        if not any(k in base for k in ("LICEN", "COPYING", "NOTICE", "AUTHORS")):
            continue
        try:
            text = dist.locate_file(f).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        inner = rel.split(".dist-info/", 1)[1]
        inner = inner[len("licenses/"):] if inner.startswith("licenses/") else inner
        out.append((inner, text.rstrip() + "\n"))
    return out


def main() -> int:
    app = _dist(APP)
    dists = _closure(APP)
    py = ".".join(map(str, sys.version_info[:3]))
    lines = [HEADER.format(today=date.today().isoformat(), version=app.version, python=py)]
    for d in dists:
        key = canonicalize_name(d.metadata["Name"])
        lines.append(
            f"| {d.metadata['Name']} | {d.version} | {_license(d)} | "
            f"{_homepage(d)} | {NOTES.get(key, '')} |"
        )
    lines.append(f"| Python | {py} | PSF-2.0 | https://www.python.org | The interpreter. |")

    lines.append("\n## License texts\n")
    lines.append("Reproduced verbatim from each package's own distribution.\n")
    for d in dists:
        key = canonicalize_name(d.metadata["Name"])
        lines.append(f"\n### {d.metadata['Name']} {d.version}\n")
        lines.append(f"License: {_license(d)}  ")
        home = _homepage(d)
        if home:
            lines.append(f"Homepage: <{home}>\n")
        files = _license_files(d)
        if not files and key in EXTERNAL_TEXTS:
            names = ", ".join(EXTERNAL_TEXTS[key])
            lines.append(
                f"The wheel ships no license file; the terms are the {names.replace('.txt', '')} "
                f"text reproduced in the *Common license texts* section below. "
                f"Copyright (C) The Qt Company Ltd. and other contributors.\n"
            )
            continue
        if not files:
            lines.append("_(no license file found in the wheel)_\n")
            continue
        for name, text in files:
            lines.append(f"\n**{name}**\n")
            lines.append("```text")
            lines.append(text.replace("```", "` ` `"))
            lines.append("```")

    lines.append("\n## Common license texts\n")
    for fname, title in (("LGPL-3.0.txt", "GNU Lesser General Public License v3.0 (PySide6, shiboken6)"),
                         ("GPL-3.0.txt", "GNU General Public License v3.0 (incorporated by the LGPL; also pylibjpeg-libjpeg)"),
                         ("PSF-2.0.txt", "Python Software Foundation License (Python)")):
        lines.append(f"\n### {title}\n")
        lines.append("```text")
        lines.append((TEXTS / fname).read_text(encoding="utf-8").rstrip().replace("```", "` ` `"))
        lines.append("```")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(dists)} packages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
